services:
  postgres:
    image: docker.io/postgres:16.2-alpine3.19
    ports:
      - 5432:5432
    volumes:
      - /data/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb

